import { describe, expect, it } from "vitest";
import { OpenCodeRuntime } from "../src/adapters/opencode/runtime.js";
import type { CommandRunner } from "../src/adapters/opencode/process.js";
import type { WorkUnit, Worker } from "../src/protocol.js";
const workUnit: WorkUnit = { id: "wu-1", goal: "Implement a bounded change", repository: "example/repo", capabilities: ["coding"], acceptanceCriteria: ["tests pass"] };
const worker: Worker = { id: "worker-opencode", capabilities: ["coding"], runtime: "opencode" };
function fakeRunner(responses: Record<string, { stdout?: string; stderr?: string; error?: Error }> = {}): CommandRunner { return { async run(command, args) { const response = responses[[command, ...args].join(" ")]; if (response?.error) throw response.error; return { stdout: response?.stdout ?? "", stderr: response?.stderr ?? "" }; } }; }
describe("OpenCodeRuntime", () => {
  it("implements the lifecycle without requiring OpenCode", async () => { const calls: string[][] = []; const runner: CommandRunner = { async run(command, args) { calls.push([command, ...args]); return { stdout: "ok", stderr: "" }; } }; const runtime = new OpenCodeRuntime({ workspaceRoot: ".tmp-test", runner }); const workspace = await runtime.createWorkspace(workUnit); const worktree = await runtime.createWorktree(workspace, "HEAD"); const agent = await runtime.startAgent(worktree, worker); await runtime.promptAgent(agent, "Implement the bounded change"); expect(await runtime.waitAgent(agent, 1000)).toBe("idle"); expect(await runtime.inspectAgent(agent)).toEqual({ status: "idle", failure: undefined }); const evidence = await runtime.collectRuntimeEvidence(agent); expect(evidence.runtime).toBe("opencode"); expect(evidence.events.map((event) => event.type)).toEqual(["prompt.started", "prompt.completed"]); expect(calls.some((call) => call[0] === "opencode" && call[1] === "run")).toBe(true); });
  it("maps an unavailable executable explicitly", async () => { const runtime = new OpenCodeRuntime({ runner: fakeRunner({ "opencode run --format json hello": { error: new Error("ENOENT: opencode not found") } }) }); const workspace = await runtime.createWorkspace(workUnit); const worktree = await runtime.createWorktree(workspace, "HEAD"); const agent = await runtime.startAgent(worktree, worker); await expect(runtime.promptAgent(agent, "hello")).rejects.toThrow("OpenCode runtime [unavailable]"); expect(await runtime.inspectAgent(agent)).toEqual({ status: "exited", failure: "unavailable" }); });
  it("keeps runtime completion separate from verification", async () => { const runtime = new OpenCodeRuntime({ runner: fakeRunner() }); const workspace = await runtime.createWorkspace(workUnit); const worktree = await runtime.createWorktree(workspace, "HEAD"); const agent = await runtime.startAgent(worktree, worker); await runtime.promptAgent(agent, "hello"); const runtimeStatus = await runtime.inspectAgent(agent); expect(runtimeStatus.status).toBe("idle"); expect("verification" in runtimeStatus).toBe(false); });
});
